version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webob
  version: latest
- name: ssl
  version: latest

builtins:
- appstats: on
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
- url: /page/signin.*
  script: main.app
  secure: always
  login: required
- url: /api/v1/.*
  script: main.app
  secure: always
  login: required
- url: /page/register.*
  script: main.app
  secure: always
  login: required
- url: /page/settings.*
  script: main.app
  secure: always
  login: required
- url: /page/invitation.*
  script: main.app
  secure: always
  login: required
- url: /_admin/.*
  script: admin.app
  secure: always
  login: admin
- url: /.*
  script: main.app
  secure: always

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (\.cache/.*)|
  (\.idea/.*)|
  (app\.yaml)|
  (app\.yml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (.*\.scss)|
  (\..*)|
  (README\.md)|
  (README\.pdf)|
  (LICENSE)|
  (google_appengine.zip)|
  (google_appengine/.*)|
  )$
